### PR TITLE
[FIX] : Error message sent in the chat room

### LINKED ISSUE #31: [Bug]: Error message being sent in quick ai command
### What happened?

While using `/quick ai` when any error comes either from the AI or error of not configuring one a user could send the error message to the chat using submit button 

### Steps to reproduce

1. call `/quick ai` command
2. click on the generate button
3. you can see the error comes in the input box if you have not setup the ai or given the api key
4. when you click on submit the error message will be sent in the room 

### This is how the bug looks like

https://github.com/user-attachments/assets/82c4ee7b-aa48-4fdb-b92d-541938b6efaa

### This is my proposed solution 

https://github.com/user-attachments/assets/61088487-d193-4ab4-90e3-baa369d1485e

with this the user can not be able to send the error message in the room 

### Version

v7.2.0

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by not-meet**
## Issue(#31 )

Closes #31 

## Acceptance Criteria fulfillment

- [x] Hides submit button if the input box shows any error

## Proposed changes 

- Added a conditional check to check if the response message has any sort of error in generating the ai message in any language
- Make the submit button undefined if there is any error and if not the logic works perfectly fine as before.

https://github.com/user-attachments/assets/61088487-d193-4ab4-90e3-baa369d1485e

### CODE REVIEW

File: src/modal/AIreplyModal.ts [hunk 1]
```diff
@@ -70,6 +70,20 @@ export async function ReplyAIModal(
 
 	blocks.push(messageblock, promptInput, secitonBlock);
 
+	const ERROR_KEYS = [
```
Comment (VipinDevelops) [inline src/modal/AIreplyModal.ts:73]: can we use something more type safe here ?

Comment (VipinDevelops) [reply src/modal/AIreplyModal.ts:73]: use enum we already have or something like that

File: src/modal/AIreplyModal.ts [hunk 2]
```diff
@@ -88,13 +102,13 @@ export async function ReplyAIModal(
...
 
-	const submit = elementBuilder.addButton(
+	const submit = !isError && response?.trim() ? elementBuilder.addButton(
 		{ text: t('Send_This_Text', language), style: ButtonStyle.PRIMARY },
 		{
 			actionId: ReplyAIModalEnum.SUBMIT_ACTION_ID,
 			blockId: ReplyAIModalEnum.SUBMIT_BLOCK_ID,
 		},
-	);
+	) : undefined;
```
Comment (VipinDevelops) [inline src/modal/AIreplyModal.ts:111]: null not undefined

**Review by VipinDevelops — CHANGES_REQUESTED** [review]
